sudo: required
services:
  - docker
before_install:
  - docker build -t mh10445:multi_client -f Dockerfile.dev .
script:
  - docker run -e CI=true mh10445:multi_client npm run test -- --coverage
after_success:
  - docker build -t mh10445:multi_client .
  - echo "$PASSWORD" | docker login -u "$USERNAME" -p --password-stdin
  - docker push mh10445:multi_client
