sudo: required
services:
  - docker
before_install:
  - docker build -t mh10445:multi_client -f Dockerfile.dev .
script:
  - docker run -e CI=true mh10445:multi_client npm run test -- --coverage
after_success:
  - docker build -t mh10445:multi_client .
  - docker login
  - docker images
  - docker login -u "$USERNAME" -p "$PASSWORD" docker.io
  - docker push mh10445:multi_client
